# .streamlit/secrets.toml
[connections.gsheets_stops_2022]
spreadsheet = "https://drive.google.com/file/d/1ufTEjK1BiA6QP7rpn15PTyjl42r4_5mZ/view?usp=drive_link"

[connections.gsheets_avl_data_corrected_2022_05]
spreadsheet = "https://drive.google.com/file/d/18iVdhyZa78jL8GO_iBHgTbUsoh3VmEd6/view?usp=drive_link"